# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      asciidoctor:
        patterns:
          - "org.asciidoctor.jvm.*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
