#!/bin/bash

__Author__="Force.Charlie"
__Date__="2015.05.25"

PrefixDir=$(cd `dirname $0`; pwd)
#echo $PrefixDir

function CheckSyntax()
{
	if [ ! -f $1 ];then
		return 1
	fi

	ret=$(awk -F= 'BEGIN{valid=1}
	{
		if(valid == 0) next
		if(length($0) == 0) next
		gsub(" |\t","",$0)
		head_char=substr($0,1,1)
		if (head_char != "#"){
			if( NF == 1){
				b=substr($0,1,1)
				len=length($0)
				e=substr($0,len,1)
				if (b != "[" || e != "]"){
					valid=0
				}
			}else if( NF == 2){
				b=substr($0,1,1)
				if (b == "["){
					valid=0
				}
			}else{
				valid=0
			}
		}
	}
	END{print valid}' $1)

	if [ $ret -eq 1 ];then
		return 0
	else
		return 2
	fi
}

function GetPrivateProfileString()
{
	if [ ! -f $1 ] || [ $# -ne 3 ];then
		return 1
	fi
	blockname=$2
	fieldname=$3

	begin_block=0
	end_block=0

	cat $1 | while read line
	do

		if [ "X$line" = "X[$blockname]" ];then
			begin_block=1
			continue
		fi

		if [ $begin_block -eq 1 ];then
			end_block=$(echo $line | awk 'BEGIN{ret=0} /^\[.*\]$/{ret=1} END{print ret}')
			if [ $end_block -eq 1 ];then
				#echo "end block"
				break
			fi

			need_ignore=$(echo $line | awk 'BEGIN{ret=0} /^#/{ret=1} /^$/{ret=1} END{print ret}')
			if [ $need_ignore -eq 1 ];then
				#echo "ignored line:" $line
				continue
			fi
			field=$(echo $line | awk -F= '{gsub(" |\t","",$1); print $1}')
			value=$(echo $line | awk -F= '{gsub(" |\t","",$2); print $2}')
			#echo "'$field':'$value'"
			if [ "X$fieldname" = "X$field" ];then
				#echo "result value:'$result'"
				echo $value
				break
			fi

		fi
	done
	return 0
}

usage(){
cat<<EOF
git-as-svn launcher helper
usage: launcher [options]
       -start          start git-as-svn
       -stop           stop git-as-svn
       -status         check git-as-svn run status
       -restart        restart git-as-svn
       -help           Print git-as-svn launcher help
EOF
exit 0
}


start(){

}

stop(){

}

restart(){

}

for arg ;do
	case "$arg" in
		-help) usage ;;
		-start) start;;
		-stop) stop;;
		-restart) restart;;
esac
done

usage

