[[_gitlab]]
= GitLab integration

:filename: _gitlab.adoc
include::_feedback.adoc[]

git-as-svn supports integration with https://gitlab.com/[GitLab] >= 9.3.3.

This includes:

* User authentication against GitLab
* Access control depending on user permissions in GitLab
* Usage of GitLab LFS server for transparent handling of LFS files for svn users
* Automatic discovery of new repositories created in GitLab
* Running GitLab repository hooks if any installed

[[_configuration]]
== Configuration

NOTE: This chapter assumes that GitLab is installed using standard Omnibus installation to `/opt/gitlab`.

git-as-svn uses direct file access to Git repositories, so it needs to run from the same user as GitLab (normally, `git`).
If you're installing both git-as-svn and Gitlab from Debian packages, no additional actions are required.

. Create GitLab https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html[Personal Access token] for git-as-svn.
Token needs to have following scopes: `api`, `sudo`, `read_repository`, `read_user`, `write_repository`. Do *not* add `read_api` scope to token.

. Change `userDB` to `!gitlabUsers`.
This will tell git-as-svn to authenticate users against GitLab server:
+
[source,yaml]
----
userDB: !gitlabUsers {}
----

. Configure builtin git-as-svn webserver:
+
[source,yaml]
----
shared:
  - !web

    # git-as-svn base url. Leave empty for autodetect.
    # Default: empty
    #
    # baseUrl: http://localhost:8123/

    listen:
      - !http

        # The network interface where git-as-svn web server binds to as an IP address or a hostname.  If 0.0.0.0, then bind to all interfaces.
        # Default: localhost
        #
        # host: localhost

        # Port where git-as-svn web server listens on.
        # Default: 8123
        #
        # port: 8123

        # HTTP idle timeout milliseconds. If not a single byte is sent or received over HTTP connection, git-as-svn closes it.
        # -1 = Use Jetty default
        # 0 = Disable timeout
        # Default: -1
        #
        # idleTimeout: -1

        # Tells git-as-svn to handle X-Forwarded-* headers.
        # Enable this if git-as-svn web server is running behind reverse HTTP proxy (like nginx)
        # Default: false
        #
        # forwarded: false
----

. Configure GitLab URL and token:
+
[source,yaml]
----
shared:
  - !gitlab

    # GitLab base URL. This must match GitLab EXTERNAL_URL.
    # Default: http://localhost/
    #
    url: <GitLab URL>

    # GitLab access token. Note that git-as-svn requires sudo access.
    token: <GitLab Access Token>
----

. Configure git-as-svn to use GitLab as repository list source:
+
[source,yaml]
----
repositoryMapping: !gitlabMapping

  # Filesystem location where GitLab stores repositories
  # Note that git-as-svn requires write access
  # Default: /var/opt/gitlab/git-data/repositories/
  #
  # path: /var/opt/gitlab/git-data/repositories/

  # Common settings for all repositories exposed to svn://
  #
  template:
    pusher: !pushEmbedded
      # This tells git-as-svn where GitLab commit hooks are located
      hooksPath: /opt/gitlab/embedded/service/gitaly-ruby/git-hooks
----

. {blank}
+
IMPORTANT: Restart git-as-svn after changing its config.
If your OS uses Systemd, this can be done via `sudo systemctl restart git-as-svn`.

. Add `git-as-svn:<branch>` topics to whatever repositories you want to add to git-as-svn via "Settings -> General -> Topics" in GitLab project settings.
For example, add `git-as-svn:master` to expose `master` branch.
If you want to expose more than one branch, add multiple `git-as-svn:<branch>` topics separated by commas.

== Supported Git LFS modes

. git-as-svn uses GitLab LFS API for write operations and direct disk access for read operations.
This is recommended option.
+
[source,yaml]
----
lfsMode: !fileLfs
  # Directory where GitLab stores LFS ojects
  path: /var/opt/gitlab/gitlab-rails/shared/lfs-objects
----

. git-as-svn uses GitLab LFS API for all LFS operations. This mode is slower than `!fileLfs`.
+
[source,yaml]
----
lfsMode: !httpLfs {}
----

. git-as-svn doesn't use LFS at all
+
[source,yaml]
----
lfsMode: null
----

== Full configuration file example

./etc/git-as-svn/git-as-svn.conf
[source,yaml]
----
include::examples/config-gitlab.yml[]
----
