[[_gitlab]]
= GitLab integration

:filename: _gitlab.adoc
include::_feedback.adoc[]

git-as-svn supports integration with https://gitlab.com/[GitLab] >= 9.3.3.

This includes:

 * User authentication against GitLab
 * Access control depending on user permissions in GitLab
 * Usage of GitLab LFS server for transparent handling of LFS files for svn users
 * Automatic discovery of new repositories created in GitLab
 * Running GitLab repository hooks if any installed

[[_configuration]]
== Configuration

git-as-svn uses direct file access to Git repositories, so it needs to run from the same user as GitLab (normally, `git`).
If you're installing both git-as-svn and Gitlab from Debian packages, no additional actions are required.

IMPORTANT: git-as-svn requires sudo https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html[access token permission].

. Change `userDB` to `!gitlabUsers`. This will tell git-as-svn to authenticate users against GitLab server:
+
[source,yaml]
----
userDB: !gitlabUsers {}
----

. Configure builtin git-as-svn webserver:
+
[source,yaml]
----
shared:
  - !web

    # git-as-svn base url. Leave empty for autodetect.
    # Default: empty
    #
    # baseUrl: http://localhost:8123/

    listen:
      - !http

        # The network interface where git-as-svn web server binds to as an IP address or a hostname.  If 0.0.0.0, then bind to all interfaces.
        # Default: localhost
        #
        # host: localhost

        # Port where git-as-svn web server listens on.
        # Default: 8123
        #
        # port: 8123

        # HTTP idle timeout milliseconds. If not a single byte is sent or received over HTTP connection, git-as-svn closes it.
        # -1 = Use Jetty default
        # 0 = Disable timeout
        # Default: -1
        #
        # idleTimeout: -1

        # Tells git-as-svn to handle X-Forwarded-* headers.
        # Enable this if git-as-svn web server is running behind reverse HTTP proxy (like nginx)
        # Default: false
        #
        # forwarded: false
----

. Configure GitLab address and token:
+
[source,yaml]
----
shared:
  - !gitlab

    # GitLab base URL. This must match GitLab EXTERNAL_URL.
    # Default: http://localhost/
    #
    # url: http://localhost/

    # Tells git-as-svn to use GitLab for LFS objects and file locking
    # Default: true
    #
    # lfs: true

    # GitLab access token. Note that git-as-svn requires sudo access.
    token: <GitLab Access Token>
----

. Add `git-as-svn:<branch>` topics to whatever repositories you want to add to git-as-svn via "Settings -> General -> Topics" in GitLab project settings.
For example, add `git-as-svn:master` to expose `master` branch. If you want to expose more than one branch,, add multiple `git-a-svn:<branch>` topics separated by commas.

IMPORTANT: With modern GitLab versions (11+), git-as-svn doesn't automatically call GitLab hooks.
See how to workaround it https://github.com/bozaro/git-as-svn/issues/271[git-as-svn issue #271].

== Full configuration file example

./etc/git-as-svn/git-as-svn.conf
[source,yaml]
----
include::examples/config-gitlab.yml[]
----
