[[_props]]
= SVN Properties

:filename: _props.adoc
include::_feedback.adoc[]

git-as-svn has limited support for http://svnbook.red-bean.com/en/1.7/svn.ref.properties.html::[Subversion Properties].

IMPORTANT::Proper operation of this feature requires Subversion client version 1.8 or later.

== .gitignore file

git-as-svn transparently builds `svn:ignore` and `svn:global-ignores` Subversion Properties based on `.gitignore` files in Git repository.

For example:

..gitignore
----
*.class
*/build
----

Results in:

----
$ svn pl -v <repo>
Properties on '<repo>':
    svn:global-ignores
        *.class

$ svn pl -v <repo>/foo/
Properties on '<repo>/foo/':
    svn:ignore
        build
----

IMPORTANT:: Negated path masks (`!/path/`) are not supported

== .gitattributes file

git-as-svn transparently builds `svn:eol-style`, `svn:mime-type` and `svn:auto-props` Subversion Properties based on `.gitattributes` files in Git repository.

For example:

..gitattributes
----
*.txt text
*.xml eol=lf
*.bin binary
----

Add property to the directory `svn:auto-props` with the contents:

----
$ svn pl -v <repo>
Properties on '<repo>':
  svn:auto-props
    *.txt = svn:eol-style=native
    *.xml = svn:eol-style=LF
    *.bin = svn:mime-type=application/octet-stream
----

Additionally, individual files that match `.gitattributes` entries, will get corresponding Subversion Properties:

----
$ svn pl -v <repo>/native.txt
Properties on '<repo>/native.txt':
  svn:eol-style
    native

$ svn pl -v '<repo>/unix.xml':
Properties on '<repo>/unix.xml':
  svn:eol-style
    LF

$ svn pl -v '<repo>/binary.bin':
  svn:mime-type
    application/octet-stream
----

== .tgitconfig file

Please, refer to https://tortoisegit.org/docs/tortoisegit/tgit-dug-settings.html#tgit-dug-settings-git[TortoiseGit documentation] on exact syntax of `.tgitconfig` file

Example:

..tgitconfig
----
[bugtraq]
    logregex = #(\\d+)
    url = https://github.com/bozaro/git-as-svn/issues/%BUGID%
    warnifnoissue = false
----

git-as-svn converts this to:

----
$ svn pl -v <repo>
Properties on '<repo>':
  bugtraq:logregex
    #(\\d+)
  bugtraq:url
    https://github.com/bozaro/git-as-svn/issues/%BUGID%
  bugtraq:warnifnoissue
    false
----

[[invalid-svn-props]]
== Commit failed: Invalid svn properties on file

If you get "Commit failed: Invalid svn properties on file" error when trying to commit a new file via git-as-svn, you need:

. Decide if this file is text or binary
* If *text*, go to `.gitattributes` and add `text` entry for your file extension.
You may optionally want to specify https://git-scm.com/docs/gitattributes#_code_eol_code[EOL behavior].
* If *binary*, go to `.gitattributes` and add `-text` entry for your file extension
. Commit `.gitattributes`
. `svn up` in working copy root
. `svn revert <new file>` (this will undo effect of `svn add`)
* `svn add <new file>` again
* Finally, `svn commit`
