[[props]]
= SVN Properties

The main `svn properties` trouble that they should be maintained in the
synchronous state between Git and Subversion.

Because of this arbitrary `svn properties` is not supported. To value
`svn properties` correspond Git-view, they are generated on the fly based on the repository content.`

Wherein:

* the commit verifies that `svn properties` file or directory exactly
match what should be according to the data repository;
* Subversion does not tool allows you to change most of the properties
(exception: `svn:executable`, `svn:special`);
* if a file affects the `svn properties` other files after changing it
`svn properties` of the files in the same change.

[IMPORTANT]
====
For user convenience, git-as-svn is actively using the inherited
properties.

This feature requires Subversion 1.8 or later.

Otherwise there will be problems with the svn properties for new files
and directories.
====

== File .gitignores

This file affects the property `svn:ignore` and `svn:global-ignores` for
the directory and its subdirectories.

For example, a file in the directory `/foo` with the contents:

----
.idea/libraries
*.class
*/build
----

Mapped to properties:

* for directory `/foo`:
+
----
svn:global-ignores: *.class
----
* for directory `/foo/*`:
+
----
svn:ignore: build
----
* for directory `/foo/.idea`:
+
----
svn:ignore: libraries build
----

[IMPORTANT]
====
For Subversion has no way to make an exception for directories, as a
result, for example, the rules of `/foo` (file or directory
`foocode>) and /foo/ (directory foo) in Subversion will work the same way, though to Git they have different behavior.`

Terms like "all but" not supported on mapping to the
`svn:global-ignores` property.
====

== File .gitattributes

This file affects the properties of the `svn:eol-style` and
`svn:mime-type` files from this directory and `svn:auto-props` from the
directory itself.

For example, a file with contents:

----
*.txt           text eol=native
*.xml           eol=lf
*.bin           binary
----

Add property to the directory `svn:auto-props` with the contents:

----
*.txt = svn:eol-style=native
*.xml = svn:eol-style=LF
*.bin = svn:mime-type=application/octet-stream
----

And files in this directory:

* for suffix `.txt` add property `svn:eol-style = navtive`
* for suffix `.xml` add property `svn:eol-style = LF`
* for suffix `.bin` add property
`svn:mime-type = application/octet-stream`

== File .tgitconfig

This file only changes the properties of the directory in which it is
located.

Properties are mapped one-to-one, for example, a file with the contents:

----
[bugtraq]
    url = https://github.com/bozaro/git-as-svn/issues/%BUGID%
    logregex = #(\\d+)
    warnifnoissue = false
----

It will be converted to properties:

* `bugtraq:url =
        https://github.com/bozaro/git-as-svn/issues/%BUGID%`
* `bugtraq:logregex = #(\\d+)`
* `bugtraq:warnifnoissue = false`

[IMPORTANT]
====
If you use bugtraq svn properties, it is highly recommended that you use
TortoiseSVN 1.9 or later.

Otherwise TortoiseSVN will attempt to set these parameters for all newly
created directories instead of use inherited properties.
====
