[[install]]
= Installation

IMPORTANT: Subversion versions prior to 1.8 are *not* supported because git-as-svn relies on https://subversion.apache.org/docs/release-notes/1.8.html#iprops[inherited properties] Subversion feature.

== .gitattributes

By default, Git uses native line ending for text files and determines whether file is text or not using heuristics
that do not match Subversion behavior.

In order to fix this discrepancy, add the following to your `.gitattributes` file:

..gitattributes
----
*   -text
----

This will force Git to store files as-is unless end-of-line conversion is explicitly configured for them.
See https://git-scm.com/docs/gitattributes[gitattributes documentation] for additional info.

== Installation on Debian/Ubuntu

You can install git-as-svn repository on Debian/Ubuntu using the following
commands:

[source,bash]
----
# Add bintray GPG key
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
# Add package source
echo "deb https://dl.bintray.com/bozaro/git-as-svn debian main" | sudo tee /etc/apt/sources.list.d/git-as-svn.list
# Install package
sudo apt-get update
sudo apt-get install git-as-svn
sudo apt-get install git-as-svn-lfs
----

=== git-as-svn package

This package contains the git-as-svn.

After you install git-as-svn is run in daemon mode and is
available on the svn-protocol on port 3690. The daemon runs as `git`
user.

To access the server, you can use the user:

Login: test

Password: test

You can check configuration with command like:

[source,bash]
----
svn ls --username test --password test svn://localhost/example/
----

==== Used directories

This package by default is configured to use the following directories:

/etc/git-as-svn::
This directory contains git-as-svn configuration files.
+
/usr/share/doc/git-as-svn::
This directory contains git-as-svn documentation.
+
/var/git/lfs::
This directory contains Git Large File Storage files.
+
It must be writable by user `git`.
+
/var/git/repositories::
This directory is used by default to store the Git-repositories.
+
It must be writable by user `git`.
+
/var/log/git-as-svn::
This directory is used to record log files.
+
It must be writable by user `git`.
+
See <<logging.adoc#logging, logging documentation>> on log configuration.
+
/var/cache/git-as-svn::
This directory is used to store the git-as-svn cache.
+
It must be writable by user `git`.
+
The loss of the contents of this directory is not critical for
operation and does not entail the loss of user data.

[[git-as-svn-lfs]]
=== git-as-svn-lfs package

This package contains the `git-lfs-authenticate` script required for <<lfs.adoc#lfs, git-as-svn builtin LFS server>>

== Manual download

To try git-as-svn you need:

1.  Install Java 8 or later;
2.  Download archive from site
https://github.com/bozaro/git-as-svn/releases/latest;
3.  After unpacking the archive change working path to the uncompressed
directory and run the command:
+
----
bin/git-as-svn -c doc/examples/config.yml
----

This will start git-as-svn server with following configuration:

1.  The server is accessible via svn-protocol on port 3690.
+
You can check server with command like:
+
----
svn ls svn://localhost/example
----
2.  To access the server, you can use the user:
+
Login: test
+
Password: test
3.  Cache and repository will be created in `build` directory:
* `example.git` — repository directory, accessible via svn-protocol;
* `git-as-svn.mapdb*` — cache files for expensive computed data.
