!config:

# Specifies IP to listen to for svn:// connections
# Default: 0.0.0.0
#
# host: 0.0.0.0

# Specifies port number to listen to for svn:// connections
# Default: 3690
#
# port: 3690

# Subversion realm name. Subversion uses this for credentials caching
# Default: git-as-svn realm
#
# realm: git-as-svn realm

# Traffic compression level. Supported values: LZ4, Zlib, None
# Default: LZ4
#
# compressionLevel: LZ4

# If enabled, git-as-svn indexed repositories in parallel during startup
# This results in higher memory usage so may require adjustments to JVM memory options
# Default: true
#
# parallelIndexing: true

# Sets cache location
cacheConfig: !persistentCache
  path: /data/cache/git-as-svn.mapdb

# Other available repository mappings: !giteaMapping, !gitlabMapping
repositoryMapping: !listMapping
  groups:
    developers:
      - test
  repositories:
    example:
      access:
        /:
          # Asterisk (*) means all users
          # $authenticated means authenticated users
          # $anonymous means anonymous users
          #
          # Supported modes: r/rw/none. Empty string also means none
          '*': r
          '@developers': rw
      repository:
        # Allowed create modes:
        # - ERROR - exit with error, if repository not exists
        # - EMPTY - create empty repository
        # - EXAMPLE - create repository with example data
        createMode: EXAMPLE
        branches:
          - master
        path: /var/git/repositories/example.git
        renameDetection: true

shared:
  # Submodule list.
  # You can define extra submodule path. Every path defined in "repositories" already included in submodule list.
  - !submodules [
  ]

  # git-as-svn builtin web server
  # It is used for GitLab system hook for repository creation/deletion notifications
  # Also, git-as-svn builtin LFS server is served through it
  - !web

    # git-as-svn base url. Leave empty for autodetect.
    # Default: empty
    #
    # baseUrl: http://localhost:8123/

    listen:
      - !http {

        # The network interface where git-as-svn web server binds to as an IP address or a hostname.  If 0.0.0.0, then bind to all interfaces.
        # Default: localhost
        #
        # host: localhost

        # Port where git-as-svn web server listens on.
        # Default: 8123
        #
        # port: 8123

        # HTTP idle timeout milliseconds. If not a single byte is sent or received over HTTP connection, git-as-svn closes it.
        # -1 = Use Jetty default
        # 0 = Disable timeout
        # Default: -1
        #
        # idleTimeout: -1

        # Tells git-as-svn to handle X-Forwarded-* headers.
        # Enable this if git-as-svn web server is running behind reverse HTTP proxy (like nginx)
        # Default: false
        #
        # forwarded: false
      }

  # Git LFS server
  - !localLfs
    # Secret token for git-lfs-authenticate script
    # secretToken:
    path: /var/git/lfs

# Other available userDBs: !ldapUsers !giteaUsers, !gitlabUsers
# Simple in-memory user database
userDB: !localUsers
  users:
    - username: test
      # Clear-text password is required to perform CRAM-MD5 authentication
      password: test
      # Email and real name are used to create Git commits
      email: test@noreply.fake
      realName: Test User

